- name: Recursively grant privileges in dataload directory
  ansible.builtin.file:
    path: '{{ ols4_base_dir }}/dataload'
    state: directory
    recurse: yes
    mode: '0777'
- name: Run docker-compose up -d
  command: 'docker-compose up -d'
  args:
    chdir: '{{ ols4_base_dir }}'
  environment:
        OLS4_CONFIG: '{{ ols4_config_file }}'
