- name: Check if legacy docker-compose is available
  ansible.builtin.command: which docker-compose
  register: docker_compose_legacy
  ignore_errors: yes

- name: Check if new docker compose plugin is available
  ansible.builtin.command: docker compose version
  register: docker_compose_plugin
  ignore_errors: yes

- name: Run docker-compose up -d (legacy)
  ansible.builtin.shell: docker-compose up -d
  args:
    chdir: '{{ ols4_base_dir }}'
  environment:
    OLS4_CONFIG: '{{ ols4_config_file }}'
  when: docker_compose_legacy.rc == 0

- name: Run docker compose up -d (plugin)
  ansible.builtin.shell: docker compose up -d
  args:
    chdir: '{{ ols4_base_dir }}'
  environment:
    OLS4_CONFIG: '{{ ols4_config_file }}'
  when: docker_compose_legacy.rc != 0 and docker_compose_plugin.rc == 0

- name: Fail if neither docker-compose nor docker compose is available
  ansible.builtin.fail:
    msg: "Neither 'docker-compose' nor 'docker compose' is available on the system."
  when: docker_compose_legacy.rc != 0 and docker_compose_plugin.rc != 0

