
- name: Stop Neo4J container
  community.docker.docker_container:
    name: '{{ neo4j_container }}'
    state: stopped

- name: Restore Neo4J database from file
  ansible.builtin.shell: 'docker run --name dump --entrypoint="/bin/bash" -v {{ neo4j_data_volume }}:/var/lib/neo4j/data neo4j -c "./bin/neo4j-admin database load --from-path=/var/lib/neo4j/data neo4j --overwrite-destination=true'
  args:
    executable: /bin/bash

- name: Remove dump container
  community.docker.docker_container:
    name: dump
    state: absent

- name: Start Neo4J container
  community.docker.docker_container:
    name: '{{ neo4j_container }}'
    state: started
