
- name: Stop Neo4J container
  community.docker.docker_container:
    name: '{{ neo4j_container }}'
    state: stopped

- name: Dump Neo4J database with timestamp in a new container
  ansible.builtin.shell: 'docker run --name dump --entrypoint="/bin/bash" -v {{ neo4j_data_volume }}:/var/lib/neo4j/data neo4j -c "./bin/neo4j-admin database dump neo4j --to-path=/var/lib/neo4j/data && mv /var/lib/neo4j/data/neo4j.dump /var/lib/neo4j/data/tsdb$(date "+%Y.%m.%d-%H.%M.%S").dump"'
  args:
    executable: /bin/bash

- name: Remove dump container
  community.docker.docker_container:
    name: dump
    state: absent

- name: Start Neo4J container
  community.docker.docker_container:
    name: '{{ neo4j_container }}'
    state: started
