
- name: mvn clean install
  command: 'mvn clean install'
  args:
    chdir: '{{ ols4_base_dir }}'
  environment:
    PATH: '{{ ansible_env.PATH }}:{{ maven_path }}'

- name: rdf2json
  command: 'java -DentityExpansionLimit=0 -DtotalEntitySizeLimit=0 -Djdk.xml.totalEntitySizeLimit=0 -Djdk.xml.entityExpansionLimit=0 -jar rdf2json/target/rdf2json-1.0-SNAPSHOT.jar --config {{ ols4_config_file }} --output {{ ols4_config_file.split(".")[0] }}_out.json'
  args:
    chdir: '{{ ols4_base_dir }}/dataload'

- name: linker
  command: 'java -jar linker/target/linker-1.0-SNAPSHOT.jar --input {{ ols4_config_file.split(".")[0] }}_out.json --output {{ ols4_config_file.split(".")[0] }}_out.jsonl'
  args:
    chdir: '{{ ols4_base_dir }}/dataload'

- name: Delete content & directory
  ansible.builtin.file:
    state: absent
    path: '{{ ols4_base_dir }}/dataload/output_csv'

- name: Creates directory
  ansible.builtin.file:
    path: '{{ ols4_base_dir }}/dataload/output_csv'
    state: directory

- name: json2neo
  command: 'java -jar json2neo/target/json2neo-1.0-SNAPSHOT.jar --input {{ ols4_config_file.split(".")[0] }}_out.jsonl --outDir {{ ols4_base_dir }}/dataload/output_csv'
  args:
    chdir: '{{ ols4_base_dir }}/dataload'

- name: json2solr
  command: 'java -jar json2solr/target/json2solr-1.0-SNAPSHOT.jar  --input {{ ols4_config_file.split(".")[0] }}_out.jsonl --outDir {{ ols4_base_dir }}/dataload/output_csv'
  args:
    chdir: '{{ ols4_base_dir }}/dataload'

- name: wget entities and autocomplete
  shell: |
    FILES=output_csv/*_*.jsonl
    for f in $FILES
    do
      echo "$f"
      if [[ $f == *_ontologies.jsonl ]] || [[ $f == *_classes.jsonl ]] || [[ $f == *_properties.jsonl ]] || [[ $f == *_individuals.jsonl ]]; then
        echo 'is being added as entity'
        wget --method POST --no-proxy -O - --server-response --content-on-error=on --header="Content-Type: application/json" --body-file $f http://{{ ols4_hostname }}:8983/solr/ols4_entities/update/json/docs?commit=true
      elif [[ $f == *_autocomplete.jsonl ]]; then
        echo 'is being added as autocomplete'
        wget --method POST --no-proxy -O - --server-response --content-on-error=on --header="Content-Type: application/json" --body-file $f http://{{ ols4_hostname }}:8983/solr/ols4_autocomplete/update/json/docs?commit=true
      fi
    done
  args:
    executable: /bin/bash
    chdir: '{{ ols4_base_dir }}/dataload'

- name: Pause for 5 seconds
  ansible.builtin.pause:
    seconds: 5

- name: wget ols4_entities
  command: 'wget --no-proxy http://{{ ols4_hostname }}:8983/solr/ols4_entities/update?commit=true'
  args:
    chdir: '{{ ols4_base_dir }}/dataload'

- name: Pause for 5 seconds
  ansible.builtin.pause:
    seconds: 5

- name: wget ols4_autocomplete
  command: 'wget --no-proxy http://{{ ols4_hostname }}:8983/solr/ols4_autocomplete/update?commit=true'
  args:
    chdir: '{{ ols4_base_dir }}/dataload'

- name: csv2neo
  command: 'java -jar csv2neo/target/csv2neo-1.0-SNAPSHOT.jar -m i -d {{ ols4_base_dir }}/dataload/output_csv -bs {{ ingest_batch_size }} -ps {{ ingest_pool_size }} -t {{ ingest_attempts }} -uri neo4j://{{ ols4_hostname }}'
  args:
    chdir: '{{ ols4_base_dir }}/dataload'


