
- hosts: all
  roles:
    - role: git
      tags:
        - prerequisites
    - role: docker
      tags:
        - prerequisites
    - role: preprocess
      tags:
        - preprocess
    - role: ols
      tags:
        - deploy
